@startuml
enum fr.esilv.simpleparql.source.model.POSITION {
SUBJECT
PREDICATE
OBJECT
}

enum fr.esilv.simpleparql.source.model.VARIABLES {
 VARIABLE
 LABEL
 TMP1
 TMP2
}
enum fr.esilv.simpleparql.source.model.PAGE {
FIRST
SECOND
THIRD
}


interface fr.esilv.simpleparql.source.converter.filter.FilterGenerator {
createSPARQLFilter(truc:String, variable:String ) : String
}

class fr.esilv.simpleparql.source.converter.filter.FilterDefault{
createSPARQLFilter(truc:String, variable:String ) : String
}
class fr.esilv.simpleparql.source.converter.filter.FilterVirtuoso{
+createSPARQLFilter(truc:String, variable:String ) : String
}
class fr.esilv.simpleparql.source.converter.filter.FilterRegex{
+createSPARQLFilter(truc:String, variable:String ) : String
}
class fr.esilv.simpleparql.source.converter.filter.FilterCommon{
+createSPARQLFilter(truc:String, variable:String ) : String
+removeIgnoredPropreties(variable:String, ignored:List<String>):String
+createSPARQLLanguageFilter(variable:String, language:String):String
}


fr.esilv.simpleparql.source.converter.filter.FilterGenerator  <|.. fr.esilv.simpleparql.source.converter.filter.FilterDefault
fr.esilv.simpleparql.source.converter.filter.FilterGenerator  <|.. fr.esilv.simpleparql.source.converter.filter.FilterVirtuoso
fr.esilv.simpleparql.source.converter.filter.FilterGenerator  <|.. fr.esilv.simpleparql.source.converter.filter.FilterRegex

note top of fr.esilv.simpleparql.source.converter.filter: generate any queries' filters.


class fr.esilv.simpleparql.source.model.Truc{
- parents : ArrayList<Pair<ParserRuleContext, Integer>>
- name : String
- position : fr.esilv.simpleparql.source.model.POSITION
- counter : int
- currentTriple : fr.esilv.simpleparql.source.model.Triple
- variables : HashMap<fr.esilv.simpleparql.source.model.VARIABLES, String>
+getCounter()
+getPosition()
+getCurrentTriple()
+getVariables()
+getName()
+getParents()
-createParentTree(ParseTree node)
-computePosition()
-find(int ruleIndex)
-generateTripleComposantes()
-clean(String text)
-generateVariables()
+isOptionnal()
+equals(Object other)
}

note top of fr.esilv.simpleparql.source.model.Truc : SimpleARQL new structure.

class fr.esilv.simpleparql.source.model.Triple{
- String subject
- String predicate
- String object
+getSubject()
+getPredicate()
+getObject()
+get(POSITION position)
}
note top of fr.esilv.simpleparql.source.model.Triple : Subject,predicate,object.


class fr.esilv.simpleparql.source.model.Constants{
+{static}  VARIABLE = " ?SimplePARQL_" : final String
+{static}  VARIABLE_LABEL = " ?label_" : final String
+{static}  VARIABLE_TMP_1 = " ?tmp_var1_" : final String
+{static}  VARIABLE_TMP_2 = " ?tmp_var2_" : final String
+{static}  RDF = " rdfs:label " : final String
+{static}  FILTER = "FILTER" : final String
+{static}  CONTAINS_BIF = "bif:contains" : final String
+{static}  CONTAINS = "CONTAINS" : final String
+{static}  UCASE = "UCASE" : final String
+{static}  STR = "STR" : final String
+{static}  AND = " && " : final String
+{static} treeToString(SimplePARQLParser parser, ParserRuleContext query)
+{static} getNodeIndex(ParseTree node)
+{static} printTree(SimplePARQLParser parser, ParserRuleContext query, String title)
+{static} getTreeOfText(String text)
}
class fr.esilv.simpleparql.source.model.Composant{
-  filter : String
-  triple : String
-  page : PAGE
+getFilter()
+getPage()
+getTriple()
+Composant(String triple, String filter, PAGE page)
}

class fr.esilv.simpleparql.source.model.SPARQLQueryGenerated{
- page : PAGE
- query :ParserRuleContext
+ SPARQLQueryGenerated(ParserRuleContext query, PAGE page)
+getQuery()
+getPage()
}
note top of fr.esilv.simpleparql.source.model.SPARQLQueryGenerated : Final SPARQL queries with page.

class fr.esilv.simpleparql.source.model.SimplePARQLQuery{
- parser : SimplePARQLParser
+SimplePARQLQuery(SimplePARQLParser parser)
+getParser()
-{static} RearrangeQuery(SimplePARQLParser parser)
-{static} getComposantesOfTriples(ParseTree triplesSameSubject)
-{static} createNewChildren(ParseTree triplesSameSubject, ArrayList<Triple> triples)
-{static} join(ArrayList<Triple> list, String delimter)
}
note top of fr.esilv.simpleparql.source.model.SimplePARQLQuery : Delete ; and  , from query.


class fr.esilv.simpleparql.source.converter.SparqlQueries{
- parser : SimplePARQLParser
- simpleARQLTrucs : ArrayList<Truc>
-counter : int
-filterGenerator : fr.esilv.simpleparql.source.converter.filter.FilterGenerator
-  page : PAGE
-generatedQueries : ArrayList<SPARQLQueryGenerated>
-{static} logger : final Logger
-optionnal : boolean
SparqlQueries(SimplePARQLParser parser, fr.esilv.simpleparql.source.converter.filter.FilterGenerator filterGenerator, PAGE page, boolean optionnal)
SparqlQueries(SimplePARQLParser parser)
SparqlQueries(SimplePARQLParser parser, fr.esilv.simpleparql.source.converter.filter.FilterGenerator filterGenerator)
SparqlQueries(SimplePARQLParser parser, boolean optionnal)
SparqlQueries(SimplePARQLParser parser, PAGE page)
addFilterToTree(Pair<ParserRuleContext, Integer> groupGraphPattern, String filterText)
addTripleToTree(Pair<ParserRuleContext, Integer> groupGraphPattern, String filterText)
containsFilter(Pair<ParserRuleContext, Integer> groupGraphPattern, String filterText)
containsTruc()
createTruc(ParseTree trucInTree)
findInTree(ParserRuleContext tree, Truc element, int ruleIndex)
generateCartesianProductTrees(SPARQLQueryGenerated tree, Truc truc)
getGreaterPage(PAGE page1, PAGE page2)
mainGenerate()
removeOptionnalTrucFromTree(SPARQLQueryGenerated tree, Truc truc)
}
note top of fr.esilv.simpleparql.source.converter.SparqlQueries: SimplePARQL SPARQL converter.



class fr.esilv.simpleparql.source.model.Composant{
-String filter
-String triple
-PAGE page
+getTriple()
+getPage()
+getFilter()
}
note top of fr.esilv.simpleparql.source.model.Composant : Triple,filter and page


class fr.esilv.simpleparql.source.converter.query.SPARQLQueryGenerator{
-truc:Truc
-generatedComposants:ArrayList<Composant>
-filterGenerator: fr.esilv.simpleparql.source.converter.filter.FilterGenerator
- page : PAGE
+SPARQLQueryGenerator(Truc truc, fr.esilv.simpleparql.source.converter.filter.FilterGenerator filterGenerator, PAGE page)
+PageThird()
+PageSecond()
+PageFirst()
+generateRessources(Truc truc, PAGE page)
+generateProprieties(Truc truc, PAGE page)
+generatelabels(Truc truc, PAGE page)
+createGeneratedTriples()
+getGeneratedComposants()
}
note top of fr.esilv.simpleparql.source.converter.query.SPARQLQueryGenerator : Generate composants in order to use in SPARQLQueries.



@enduml